Added ASL tutorial
LLK/scratch-gui pull request #7768
Opened 2021-10-25 16:35 UTC by zoebentley

Changes: 
- adds thumbnail file for Getting Started ASL to "thumbnails" folder
- adds wistia link to translate-video.JS
- links the thumbnail file in "index.jsx"
- adds the Getting Started ASL tutorial to the tutorials in "index.jsx"
- makes it so that the original Getting Started video points to "Getting Started ASL" as one if its 2 follow-up tutorial suggestions

2021-10-26 18:31 UTC, seotts requested changes
This is awesome. I found one small (but consequential) bug, and also made one other minor suggestion.

2021-10-26 18:31 UTC, seotts commented on src/lib/libraries/decks/index.jsx
> +                'getting-started-ASL',
```suggestion
                'intro-getting-started-ASL',
```

2021-10-26 18:31 UTC, seotts commented on src/lib/libraries/decks/index.jsx
> +                'getting-started-ASL',
If I understand how this file works, I think it should be this.

2021-10-26 18:31 UTC, seotts commented on src/lib/libraries/decks/index.jsx
> +                description="Name for the 'Getting Started ASL' how-to"
I wonder if it would be helpful for the translators to have ASL written out as "American Sign Language" in the description text?

2021-10-27 19:30 UTC, zoebentley commented on src/lib/libraries/decks/index.jsx
> +                description="Name for the 'Getting Started ASL' how-to"
Sounds great

2021-10-27 19:31 UTC, zoebentley commented on src/lib/libraries/decks/index.jsx
> +                'getting-started-ASL',
Oh - thanks so much for the catch!

2021-11-03 14:49 UTC, merged