Gha migration
LLK/scratch-gui pull request #9330
Opened 2023-11-02 13:32 UTC by delasare

### Resolves

_What Github issue does this resolve (please include link)?_

- Resolves #

### Proposed Changes

_Describe what this Pull Request does_

### Reason for Changes

_Explain why these changes should be made_

### Test Coverage

_Please show how you have added tests to cover your changes_

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Safari
 
Windows
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

2023-11-14 20:03 UTC, AlexisGoodfellow commented on package.json
> -    "prepare": "husky install",
Good riddance!

2023-11-15 16:32 UTC, cwillisf requested changes
I noticed a couple small changes that I think are needed to keep consistent with previous behavior, but it's looking good!

2023-11-15 16:32 UTC, cwillisf commented on .github/workflows/ci-cd.yml
> +                  cache: "npm"
I believe this line tells the `setup-node` action to cache the npm package cache, so the "Cache node_modules" item further down shouldn't be necessary

2023-11-15 16:32 UTC, cwillisf commented on .github/workflows/ci-cd.yml
> +              run: npm install
```suggestion
              run: npm ci
```

2023-11-15 16:32 UTC, cwillisf commented on .github/workflows/ci-cd.yml
> +                  cache: "npm"
Oh, never mind. I see now that you're using those cache items to carry files to the other jobs.

2023-11-15 16:32 UTC, cwillisf commented on .github/workflows/ci-cd.yml
> +              run: npm run build
```suggestion
            - name: Run Build
              env:
                NODE_ENV: production
              run: npm run build
```

2023-11-15 16:32 UTC, cwillisf commented on .github/workflows/ci-cd.yml
> +                ${{ steps.setup-chrome.outputs.chrome-path }} --version
:sunglasses:

2023-11-15 19:03 UTC, cwillisf approved these changes
:+1: :rocket:

2023-11-27 13:59 UTC, merged